//! Generates the UI's TypeScript types and checks the committed copies are current.
//!
//! `MI_UPDATE_BINDINGS=1 cargo test -p mi-types --test bindings` rewrites
//! `ui/src/types/generated/`; without the variable the test fails when any file differs, is
//! missing, or is no longer generated.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use mi_types::*;
use ts_rs::{Config, TS};

/// Every root type the UI uses; ts-rs adds their dependencies.
fn export_all(cfg: &Config) {
    macro_rules! export {
        ($($t:ty),* $(,)?) => { $( <$t as TS>::export_all(cfg).expect(stringify!($t)); )* };
    }
    export!(
        // media
        FileId,
        MediaFile,
        FileRole,
        Probe,
        VideoInfo,
        AudioStream,
        SubtitleStream,
        Chapter,
        ScanSummary,
        PlayAllInfo,
        ScanWarning,
        // catalog and reference text
        ProviderId,
        ShowRef,
        Show,
        ShowCandidate,
        EpisodeOrdering,
        EpisodeKey,
        Episode,
        TextKind,
        ReferenceText,
        Attribution,
        // transcripts
        SpeechModel,
        SampleWindow,
        FilterReason,
        Segment,
        Transcript,
        // matching
        Signals,
        QuotePart,
        PlayAllPosition,
        EvidenceNote,
        Evidence,
        Candidate,
        Verdict,
        Confidence,
        Suggestion,
        FileMatch,
        ReviewDecision,
        // jobs
        JobId,
        JobRequest,
        Stage,
        StageState,
        FileStatus,
        Accelerator,
        JobEvent,
        JobResults,
        RecentJob,
        // settings and sources
        Settings,
        ApiKeyProvider,
        SourceState,
        SourceStatus,
        // saving and history
        NamingScheme,
        SaveModeKind,
        SaveMode,
        FileDecision,
        RenamePlanRequest,
        RenameItem,
        UntouchedReason,
        UntouchedFile,
        PlanConflict,
        RenamePlan,
        HistoryId,
        OperationFailure,
        RenameOutcome,
        HistoryItem,
        HistoryEntry,
        UndoOutcome,
        // models and updates
        ModelInfo,
        ModelState,
        ModelStatus,
        UpdateInfo,
        UpdateCheck,
        UpdateEvent,
        // errors
        ErrorCode,
        ApiError,
    );
}

const HEADER: &str = "// Generated by `cargo test -p mi-types --test bindings`. Do not edit.\n";

fn generate(dir: &Path) {
    let cfg = Config::new().with_out_dir(dir).with_large_int("number");
    export_all(&cfg);

    let mut events = String::from(HEADER);
    for (name, channel) in mi_types::events::ALL {
        events.push_str(&format!("export const {name} = \"{channel}\";\n"));
    }
    std::fs::write(dir.join("events.ts"), events).unwrap();

    let mut modules: Vec<String> = std::fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".ts") && n != "index.ts" && n != "events.ts")
        .map(|n| n.trim_end_matches(".ts").to_owned())
        .collect();
    modules.sort();
    let mut index = String::from(HEADER);
    for m in &modules {
        index.push_str(&format!("export type {{ {m} }} from \"./{m}\";\n"));
    }
    index.push_str("export * from \"./events\";\n");
    std::fs::write(dir.join("index.ts"), index).unwrap();
}

fn read_dir_files(dir: &Path) -> BTreeMap<String, String> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return BTreeMap::new();
    };
    entries
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|x| x == "ts"))
        .map(|p| {
            let name = p.file_name().unwrap().to_string_lossy().into_owned();
            (name, std::fs::read_to_string(&p).unwrap())
        })
        .collect()
}

fn committed_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../ui/src/types/generated")
}

#[test]
fn typescript_bindings_are_current() {
    let tmp = std::env::temp_dir().join(format!("mi-bindings-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).unwrap();
    generate(&tmp);
    let fresh = read_dir_files(&tmp);
    std::fs::remove_dir_all(&tmp).unwrap();

    let dir = committed_dir();
    if std::env::var("MI_UPDATE_BINDINGS").is_ok_and(|v| v == "1") {
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        for (name, content) in &fresh {
            std::fs::write(dir.join(name), content).unwrap();
        }
        return;
    }

    let committed = read_dir_files(&dir);
    let stale: Vec<&String> = fresh
        .keys()
        .chain(committed.keys())
        .filter(|name| fresh.get(*name) != committed.get(*name))
        .collect();
    assert!(
        stale.is_empty(),
        "ui/src/types/generated is stale ({stale:?}); run \
         `MI_UPDATE_BINDINGS=1 cargo test -p mi-types --test bindings`"
    );
}
