//! Runs mi-media against real ffmpeg and ffprobe on small files generated by the test.
//!
//! Two sets of programs are involved:
//! - **Under test**: `MI_FFMPEG`/`MI_FFPROBE` when set, else the built sidecars in
//!   `src-tauri/binaries/` for this platform when they are real files, else `ffmpeg`/`ffprobe` on
//!   `PATH`. This is how the minimal sidecar build is checked against the exact command lines the
//!   crate uses.
//! - **Fixture generator**: `MI_TEST_FIXTURE_FFMPEG`, else `ffmpeg` on `PATH`. It must be a full
//!   build (lavfi sources and the ac3, mpeg2video, subrip, ass and mov_text encoders), which the
//!   minimal sidecar deliberately is not.
//!
//! When either is missing the tests print why and pass without checking anything, so
//! `cargo test` works on machines without ffmpeg. `MI_REQUIRE_FFMPEG_TESTS=1` turns a missing
//! program into a failure; use it wherever ffmpeg is expected to be installed.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::OnceLock;

use mi_media::{
    ExtractOptions, MediaError, ScanOptions, Sidecars, extract_audio, extract_text_subtitles,
    probe, scan_folder, stream_audio,
};
use mi_types::{CancelFlag, DiscFolderFormat, FileRole, SampleWindow, ScanWarning};

struct Env {
    sidecars: Sidecars,
    fixtures: tempfile::TempDir,
}

fn env() -> Option<&'static Env> {
    static ENV: OnceLock<Option<Env>> = OnceLock::new();
    ENV.get_or_init(|| {
        let required = std::env::var("MI_REQUIRE_FFMPEG_TESTS").is_ok_and(|v| v == "1");
        let skip = |why: String| {
            assert!(!required, "MI_REQUIRE_FFMPEG_TESTS=1 but {why}");
            eprintln!("skipping ffmpeg tests: {why}");
            None
        };
        let Some(sidecars) = tools_under_test() else {
            return skip("no ffmpeg/ffprobe to test (set MI_FFMPEG and MI_FFPROBE)".into());
        };
        let generator = std::env::var_os("MI_TEST_FIXTURE_FFMPEG")
            .map(PathBuf::from)
            .or_else(|| find_on_path("ffmpeg"));
        let Some(generator) = generator else {
            return skip("no full ffmpeg to generate fixtures (MI_TEST_FIXTURE_FFMPEG)".into());
        };
        eprintln!(
            "ffmpeg tests: testing {} and {}, fixtures made with {}",
            sidecars.ffmpeg.display(),
            sidecars.ffprobe.display(),
            generator.display()
        );
        let fixtures = tempfile::tempdir().expect("temp dir");
        make_fixtures(&generator, fixtures.path());
        make_codec_matrix(&generator, fixtures.path());
        Some(Env { sidecars, fixtures })
    })
    .as_ref()
}

fn exe(name: &str) -> String {
    format!("{name}{}", std::env::consts::EXE_SUFFIX)
}

/// The first usable `name` on `PATH`. Empty files are skipped: on Windows `cargo test` puts
/// `target\debug` on `PATH`, and the Tauri build leaves empty sidecar placeholders there
/// (`ffmpeg.exe`), which Windows refuses to run.
fn find_on_path(name: &str) -> Option<PathBuf> {
    std::env::split_paths(&std::env::var_os("PATH")?)
        .map(|dir| dir.join(exe(name)))
        .find(|p| usable(p))
}

fn usable(path: &Path) -> bool {
    std::fs::metadata(path).is_ok_and(|m| m.is_file() && m.len() > 0)
}

fn host_triple() -> Option<&'static str> {
    match (std::env::consts::ARCH, std::env::consts::OS) {
        ("aarch64", "macos") => Some("aarch64-apple-darwin"),
        ("x86_64", "windows") => Some("x86_64-pc-windows-msvc"),
        _ => None,
    }
}

fn tools_under_test() -> Option<Sidecars> {
    if let (Some(ffmpeg), Some(ffprobe)) = (
        std::env::var_os("MI_FFMPEG"),
        std::env::var_os("MI_FFPROBE"),
    ) {
        return Some(Sidecars {
            ffmpeg: ffmpeg.into(),
            ffprobe: ffprobe.into(),
        });
    }
    if let Some(triple) = host_triple() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src-tauri/binaries");
        let ffmpeg = dir.join(exe(&format!("ffmpeg-{triple}")));
        let ffprobe = dir.join(exe(&format!("ffprobe-{triple}")));
        if usable(&ffmpeg) && usable(&ffprobe) {
            return Some(Sidecars { ffmpeg, ffprobe });
        }
    }
    Some(Sidecars {
        ffmpeg: find_on_path("ffmpeg")?,
        ffprobe: find_on_path("ffprobe")?,
    })
}

fn run(generator: &Path, args: &[&str]) {
    let out = Command::new(generator)
        .args(["-hide_banner", "-v", "error", "-y"])
        .args(args)
        .output()
        .expect("run fixture ffmpeg");
    assert!(
        out.status.success(),
        "fixture ffmpeg {args:?} failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

/// A tone whose frequency steps from 300 Hz (0-10 s) to 600 Hz (10-20 s) to 900 Hz (20-30 s), so
/// the time a window really starts at can be checked from its pitch.
const STEPPED_TONE: &str =
    "aevalsrc=0.5*sin(2*PI*if(lt(t\\,10)\\,300\\,if(lt(t\\,20)\\,600\\,900))*t):s=48000:d=30";

fn tone(frequency: u32, seconds: f64) -> String {
    format!("sine=frequency={frequency}:sample_rate=48000:duration={seconds}")
}

fn video(seconds: f64) -> String {
    format!("color=c=black:s=64x48:r=5:d={seconds}")
}

fn write(path: impl AsRef<Path>, text: &str) {
    std::fs::write(path, text).unwrap();
}

/// Writes an ffmetadata file with one chapter per length.
fn chapters_file(path: &Path, lengths: &[f64]) {
    let mut text = String::from(";FFMETADATA1\n");
    let mut start = 0.0;
    for (i, len) in lengths.iter().enumerate() {
        let end = start + len;
        text.push_str(&format!(
            "[CHAPTER]\nTIMEBASE=1/1000\nSTART={}\nEND={}\ntitle=Chapter {:02}\n",
            (start * 1000.0) as u64,
            (end * 1000.0) as u64,
            i + 1
        ));
        start = end;
    }
    write(path, &text);
}

#[rustfmt::skip]
fn make_fixtures(g: &Path, dir: &Path) {
    let p = |name: &str| dir.join(name).to_string_lossy().into_owned();
    let srt = p("lines.srt");
    write(
        &srt,
        "1\n00:00:01,000 --> 00:00:03,000\nConjunction junction,\nwhat's your function?\n\n\
         2\n00:00:04,000 --> 00:00:06,000\nHooking up words and phrases\n",
    );
    let ass = p("lines.ass");
    write(
        &ass,
        "[Script Info]\nScriptType: v4.00+\n\n[V4+ Styles]\n\
         Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n\
         Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1\n\n\
         [Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n\
         Dialogue: 0,0:00:01.00,0:00:03.00,Default,,0,0,0,,{\\i1}Lolly, lolly, lolly{\\i0}, get your adverbs here\n",
    );
    chapters_file(&dir.join("tone.ffmeta"), &[10.0, 10.0, 10.0]);

    // tone.mkv: MPEG-2 video, stereo AC-3 at 48 kHz (the common DVD case), three chapters, an
    // English SubRip stream and an ASS stream.
    run(
        g,
        &[
            "-f", "lavfi", "-i", &video(30.0),
            "-f", "lavfi", "-i", STEPPED_TONE,
            "-i", &srt, "-i", &ass, "-i", &p("tone.ffmeta"),
            "-map", "0:v", "-map", "1:a", "-map", "2:s", "-map", "3:s",
            "-map_metadata", "4", "-map_chapters", "4",
            "-c:v", "mpeg2video", "-c:a", "ac3", "-ac", "2", "-c:s:0", "srt", "-c:s:1", "ass",
            "-metadata:s:a:0", "language=eng", "-metadata:s:s:0", "language=eng",
            &p("tone.mkv"),
        ],
    );
    // two-languages.mkv: Spanish 300 Hz default stream, English 900 Hz second stream.
    run(
        g,
        &[
            "-f", "lavfi", "-i", &tone(300, 5.0),
            "-f", "lavfi", "-i", &tone(900, 5.0),
            "-map", "0:a", "-map", "1:a", "-c:a", "ac3",
            "-metadata:s:a:0", "language=spa", "-metadata:s:a:1", "language=eng",
            "-disposition:a:0", "default", "-disposition:a:1", "0",
            &p("two-languages.mkv"),
        ],
    );
    // subs.mp4: AAC audio with an MP4 text (mov_text) subtitle stream.
    run(
        g,
        &[
            "-f", "lavfi", "-i", &tone(440, 8.0), "-i", &srt,
            "-map", "0:a", "-map", "1:s", "-c:a", "aac", "-c:s", "mov_text",
            &p("subs.mp4"),
        ],
    );
    // silent-video.mkv: video only.
    run(g, &["-f", "lavfi", "-i", &video(25.0), "-c:v", "mpeg2video", &p("silent-video.mkv")]);

    // disc/: a ripped disc. Three short titles, a play-all with one chapter per title plus one
    // title that was not ripped (12 s), a short menu, an unreadable file, a macOS metadata file
    // and a VIDEO_TS folder.
    let disc = dir.join("SCHOOLHOUSE_ROCK_D1");
    std::fs::create_dir(&disc).unwrap();
    let d = |name: &str| disc.join(name).to_string_lossy().into_owned();
    let shorts = [(25.0, 300), (30.0, 500), (28.0, 700)];
    for (i, (len, freq)) in shorts.iter().enumerate() {
        run(
            g,
            &[
                "-f", "lavfi", "-i", &tone(*freq, *len), "-c:a", "ac3",
                &d(&format!("title_t{:02}.mkv", i + 1)),
            ],
        );
    }
    chapters_file(&dir.join("play-all.ffmeta"), &[25.0, 30.0, 12.0, 28.0]);
    run(
        g,
        &[
            "-f", "lavfi", "-i", &tone(400, 95.0), "-i", &p("play-all.ffmeta"),
            "-map", "0:a", "-map_chapters", "1", "-c:a", "ac3",
            &d("title_t00.mkv"),
        ],
    );
    run(g, &["-f", "lavfi", "-i", &tone(200, 5.0), "-c:a", "ac3", &d("title_t04.mkv")]);
    write(d("title_t05.mkv"), "this is not a video file");
    write(d("._title_t01.mkv"), "AppleDouble metadata");
    std::fs::create_dir(disc.join("VIDEO_TS")).unwrap();
    write(d("VIDEO_TS/VTS_01_1.VOB"), "dvd");
}

/// One file per container and audio codec the sidecar build must read: (file name, encoder,
/// extra output options, codec name ffprobe reports).
const CODEC_MATRIX: &[(&str, &str, &[&str], &str)] = &[
    ("eac3.mkv", "eac3", &[], "eac3"),
    ("dts.mkv", "dca", &["-strict", "-2"], "dts"),
    ("truehd.mkv", "truehd", &["-strict", "-2"], "truehd"),
    ("flac.mkv", "flac", &[], "flac"),
    ("opus.mkv", "libopus", &[], "opus"),
    (
        "vorbis.mkv",
        "vorbis",
        &["-strict", "-2", "-ac", "2"],
        "vorbis",
    ),
    ("aac.mp4", "aac", &[], "aac"),
    ("alac.mov", "alac", &[], "alac"),
    ("aac.m4v", "aac", &[], "aac"),
    ("mp3.avi", "libmp3lame", &[], "mp3"),
    ("pcm.avi", "pcm_s16le", &[], "pcm_s16le"),
    ("mp2.mpg", "mp2", &[], "mp2"),
    ("ac3.vob", "ac3", &["-f", "vob"], "ac3"),
    ("lpcm.vob", "pcm_dvd", &["-f", "vob"], "pcm_dvd"),
    ("ac3.ts", "ac3", &[], "ac3"),
    ("lpcm.m2ts", "pcm_bluray", &[], "pcm_bluray"),
    ("aac.mts", "aac", &[], "aac"),
];

#[rustfmt::skip]
fn make_codec_matrix(g: &Path, dir: &Path) {
    let codecs = dir.join("codecs");
    std::fs::create_dir(&codecs).unwrap();
    for (name, encoder, extra, _) in CODEC_MATRIX {
        let out = codecs.join(name).to_string_lossy().into_owned();
        let mut args = vec!["-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=3"];
        args.extend(["-c:a", encoder]);
        args.extend(extra.iter().copied());
        args.push(&out);
        run(g, &args);
    }
}

fn fixture(env: &Env, name: &str) -> PathBuf {
    env.fixtures.path().join(name)
}

/// Dominant frequency from the zero-crossing rate (two crossings per cycle).
fn frequency(samples: &[f32]) -> f64 {
    let crossings = samples
        .windows(2)
        .filter(|w| (w[0] < 0.0) != (w[1] < 0.0))
        .count();
    crossings as f64 / 2.0 / (samples.len() as f64 / 16_000.0)
}

fn near(actual: f64, expected: f64, tolerance: f64) -> bool {
    (actual - expected).abs() <= tolerance
}

#[test]
fn probes_streams_chapters_and_subtitles() {
    let Some(env) = env() else { return };
    let p = probe(&env.sidecars, &fixture(env, "tone.mkv"), &CancelFlag::new()).unwrap();
    assert!(near(p.duration_s, 30.0, 0.2), "{}", p.duration_s);
    assert!(p.container.contains("matroska"), "{}", p.container);
    let v = p.video.expect("video stream");
    assert_eq!((v.width, v.height), (64, 48));
    assert_eq!(p.audio_streams.len(), 1);
    let a = &p.audio_streams[0];
    assert_eq!(
        (a.codec.as_str(), a.channels, a.sample_rate),
        ("ac3", 2, 48_000)
    );
    assert_eq!(a.language.as_deref(), Some("eng"));
    assert_eq!(p.chapters.len(), 3);
    assert!(near(p.chapters[1].start_s, 10.0, 0.01));
    assert_eq!(p.chapters[2].title.as_deref(), Some("Chapter 03"));
    let codecs: Vec<(&str, bool)> = p
        .subtitle_streams
        .iter()
        .map(|s| (s.codec.as_str(), s.is_text))
        .collect();
    assert_eq!(codecs, [("subrip", true), ("ass", true)]);

    let mp4 = probe(&env.sidecars, &fixture(env, "subs.mp4"), &CancelFlag::new()).unwrap();
    assert_eq!(mp4.subtitle_streams[0].codec, "mov_text");
    assert!(mp4.subtitle_streams[0].is_text);
}

#[test]
fn probe_reports_unreadable_files_and_cancellation() {
    let Some(env) = env() else { return };
    let bad = fixture(env, "SCHOOLHOUSE_ROCK_D1/title_t05.mkv");
    let err = probe(&env.sidecars, &bad, &CancelFlag::new()).unwrap_err();
    assert!(matches!(err, MediaError::ToolFailed { .. }), "{err:?}");

    let cancelled = CancelFlag::new();
    cancelled.cancel();
    let err = probe(&env.sidecars, &fixture(env, "tone.mkv"), &cancelled).unwrap_err();
    assert!(matches!(err, MediaError::Cancelled), "{err:?}");
}

#[test]
fn decodes_whole_file_to_16khz_mono() {
    let Some(env) = env() else { return };
    let pcm = extract_audio(
        &env.sidecars,
        &fixture(env, "tone.mkv"),
        &ExtractOptions::default(),
        &CancelFlag::new(),
    )
    .unwrap();
    assert_eq!(pcm.sample_rate, 16_000);
    assert_eq!(pcm.start_s, 0.0);
    assert!(near(pcm.duration_s(), 30.0, 0.1), "{}", pcm.duration_s());
    let peak = pcm.samples.iter().fold(0f32, |m, s| m.max(s.abs()));
    assert!((0.3..=1.0).contains(&peak), "peak {peak}");
    // Each third of the file has its own pitch.
    let third = pcm.samples.len() / 3;
    for (i, expected) in [300.0, 600.0, 900.0].iter().enumerate() {
        let f = frequency(&pcm.samples[i * third + 1600..(i + 1) * third - 1600]);
        assert!(near(f, *expected, 10.0), "third {i}: {f} Hz");
    }
}

#[test]
fn decodes_a_window_from_its_exact_start() {
    let Some(env) = env() else { return };
    let options = ExtractOptions {
        window: Some(SampleWindow {
            start_s: 18.0,
            end_s: 22.0,
        }),
        ..ExtractOptions::default()
    };
    let pcm = extract_audio(
        &env.sidecars,
        &fixture(env, "tone.mkv"),
        &options,
        &CancelFlag::new(),
    )
    .unwrap();
    assert_eq!(pcm.start_s, 18.0);
    assert!(near(pcm.duration_s(), 4.0, 0.05), "{}", pcm.duration_s());
    // 18-20 s is 600 Hz and 20-22 s is 900 Hz: the window starts where it was asked to.
    let (first, second) = pcm.samples.split_at(32_000);
    assert!(near(frequency(&first[800..31_200]), 600.0, 10.0));
    assert!(near(frequency(&second[800..]), 900.0, 10.0));
}

#[test]
fn windows_past_the_end_are_short_or_empty() {
    let Some(env) = env() else { return };
    let path = fixture(env, "tone.mkv");
    let window = |start_s, end_s| ExtractOptions {
        window: Some(SampleWindow { start_s, end_s }),
        ..ExtractOptions::default()
    };
    let tail = extract_audio(
        &env.sidecars,
        &path,
        &window(27.0, 40.0),
        &CancelFlag::new(),
    )
    .unwrap();
    assert!(near(tail.duration_s(), 3.0, 0.1), "{}", tail.duration_s());
    let none = extract_audio(
        &env.sidecars,
        &path,
        &window(45.0, 50.0),
        &CancelFlag::new(),
    )
    .unwrap();
    assert!(none.samples.is_empty());
}

#[test]
fn streams_one_second_chunks_and_stops_early() {
    let Some(env) = env() else { return };
    let path = fixture(env, "tone.mkv");
    let mut chunks = Vec::new();
    stream_audio(
        &env.sidecars,
        &path,
        &ExtractOptions::default(),
        &CancelFlag::new(),
        &mut |c| {
            chunks.push((c.start_s, c.samples.len()));
            true
        },
    )
    .unwrap();
    assert!(chunks.len() >= 30, "{}", chunks.len());
    for (i, (start, len)) in chunks.iter().enumerate() {
        assert!(near(*start, i as f64, 1e-9), "chunk {i} starts at {start}");
        if i + 1 < chunks.len() {
            assert_eq!(*len, 16_000, "chunk {i}");
        }
    }

    let mut seen = 0;
    stream_audio(
        &env.sidecars,
        &path,
        &ExtractOptions::default(),
        &CancelFlag::new(),
        &mut |_| {
            seen += 1;
            seen < 2
        },
    )
    .unwrap();
    assert_eq!(seen, 2);
}

#[test]
fn cancelling_stops_decoding() {
    let Some(env) = env() else { return };
    let cancel = CancelFlag::new();
    let mut chunks = 0;
    let err = stream_audio(
        &env.sidecars,
        &fixture(env, "tone.mkv"),
        &ExtractOptions::default(),
        &cancel,
        &mut |_| {
            chunks += 1;
            cancel.cancel();
            true
        },
    )
    .unwrap_err();
    assert!(matches!(err, MediaError::Cancelled), "{err:?}");
    assert_eq!(chunks, 1);
}

#[test]
fn picks_the_stream_by_language_or_default() {
    let Some(env) = env() else { return };
    let path = fixture(env, "two-languages.mkv");
    let decode = |language: Option<&str>, stream_index: Option<u32>| {
        let pcm = extract_audio(
            &env.sidecars,
            &path,
            &ExtractOptions {
                language: language.map(str::to_owned),
                stream_index,
                ..ExtractOptions::default()
            },
            &CancelFlag::new(),
        )
        .unwrap();
        frequency(&pcm.samples[1600..pcm.samples.len() - 1600])
    };
    assert!(near(decode(None, None), 300.0, 10.0), "default stream");
    assert!(
        near(decode(Some("en"), None), 900.0, 10.0),
        "English stream"
    );
    assert!(
        near(decode(Some("de"), Some(1)), 900.0, 10.0),
        "explicit index wins"
    );
}

#[test]
fn a_file_without_audio_is_reported() {
    let Some(env) = env() else { return };
    let err = extract_audio(
        &env.sidecars,
        &fixture(env, "silent-video.mkv"),
        &ExtractOptions::default(),
        &CancelFlag::new(),
    )
    .unwrap_err();
    assert!(matches!(err, MediaError::NoAudio(_)), "{err:?}");
}

#[test]
fn extracts_text_subtitles_as_srt() {
    let Some(env) = env() else { return };
    let cancel = CancelFlag::new();
    let srt = extract_text_subtitles(&env.sidecars, &fixture(env, "tone.mkv"), 2, &cancel).unwrap();
    assert!(srt.contains("00:00:01,000 --> 00:00:03,000"), "{srt}");
    assert!(srt.contains("Conjunction junction,"), "{srt}");
    assert!(srt.contains("Hooking up words and phrases"), "{srt}");

    let from_ass =
        extract_text_subtitles(&env.sidecars, &fixture(env, "tone.mkv"), 3, &cancel).unwrap();
    assert!(from_ass.contains("Lolly, lolly, lolly"), "{from_ass}");
    assert!(
        !from_ass.contains("{\\i1}"),
        "ASS override tags are converted: {from_ass}"
    );

    let from_mp4 =
        extract_text_subtitles(&env.sidecars, &fixture(env, "subs.mp4"), 1, &cancel).unwrap();
    assert!(from_mp4.contains("what's your function?"), "{from_mp4}");

    // Stream 1 of tone.mkv is audio: not a text subtitle.
    let err =
        extract_text_subtitles(&env.sidecars, &fixture(env, "tone.mkv"), 1, &cancel).unwrap_err();
    assert!(matches!(err, MediaError::ToolFailed { .. }), "{err:?}");
}

#[test]
fn scans_a_ripped_disc_folder() {
    let Some(env) = env() else { return };
    let folder = fixture(env, "SCHOOLHOUSE_ROCK_D1");
    let s = scan_folder(
        &env.sidecars,
        &folder,
        &ScanOptions::default(),
        &CancelFlag::new(),
    )
    .unwrap();

    let roles: Vec<(&str, FileRole)> = s.files.iter().map(|f| (f.id.0.as_str(), f.role)).collect();
    assert_eq!(
        roles,
        [
            ("title_t00.mkv", FileRole::PlayAll),
            ("title_t01.mkv", FileRole::Candidate),
            ("title_t02.mkv", FileRole::Candidate),
            ("title_t03.mkv", FileRole::Candidate),
            ("title_t04.mkv", FileRole::Ignored),
            ("title_t05.mkv", FileRole::Ignored),
        ]
    );
    assert_eq!(s.candidate_count, 3);
    assert_eq!(s.show_guess.as_deref(), Some("Schoolhouse Rock"));
    let play_all = s.play_all.as_ref().expect("play-all");
    assert_eq!(play_all.chapter_count, 4);
    assert_eq!(play_all.chapters_matched, 3);
    assert!(near(play_all.candidates_total_s, 83.0, 0.5));
    // Chapters all match; the duration is 14% over the files found (a title was not ripped).
    assert!(play_all.confidence > 0.7, "{}", play_all.confidence);

    assert!(s.files[5].probe.is_none());
    assert!(s.warnings.contains(&ScanWarning::MissingShortTitles {
        chapters: 4,
        short_files: 3
    }));
    assert!(s.warnings.contains(&ScanWarning::UnsupportedDiscFolder {
        folder: "VIDEO_TS".into(),
        format: DiscFolderFormat::Dvd
    }));
    assert!(
        s.warnings.iter().any(|w| matches!(
            w,
            ScanWarning::Unreadable { file_id, reason }
                if file_id.0 == "title_t05.mkv" && reason.starts_with("The file could not be read")
        )),
        "{:?}",
        s.warnings
    );
    assert_eq!(s.warnings.len(), 3, "{:?}", s.warnings);
}

#[test]
fn scanning_reports_files_without_audio() {
    let Some(env) = env() else { return };
    let dir = tempfile::tempdir().unwrap();
    std::fs::copy(fixture(env, "silent-video.mkv"), dir.path().join("a.mkv")).unwrap();
    let s = scan_folder(
        &env.sidecars,
        dir.path(),
        &ScanOptions::default(),
        &CancelFlag::new(),
    )
    .unwrap();
    assert_eq!(s.files[0].role, FileRole::Ignored);
    assert_eq!(
        s.warnings,
        [ScanWarning::NoAudio {
            file_id: mi_types::FileId("a.mkv".into())
        }]
    );
}

#[test]
fn reads_every_supported_container_and_audio_codec() {
    let Some(env) = env() else { return };
    for (name, _, _, codec) in CODEC_MATRIX {
        let path = fixture(env, &format!("codecs/{name}"));
        let p = probe(&env.sidecars, &path, &CancelFlag::new())
            .unwrap_or_else(|e| panic!("{name}: probe failed: {e}"));
        assert_eq!(p.audio_streams[0].codec, *codec, "{name}");
        assert!(near(p.duration_s, 3.0, 0.2), "{name}: {} s", p.duration_s);
        let pcm = extract_audio(
            &env.sidecars,
            &path,
            &ExtractOptions::default(),
            &CancelFlag::new(),
        )
        .unwrap_or_else(|e| panic!("{name}: decode failed: {e}"));
        assert!(
            near(pcm.duration_s(), 3.0, 0.15),
            "{name}: {} s decoded",
            pcm.duration_s()
        );
        let f = frequency(&pcm.samples[1600..pcm.samples.len() - 1600]);
        assert!(near(f, 440.0, 10.0), "{name}: {f} Hz");
    }
}
